changes done for s3bucket creation

diff --git a/.github/workflows/DeployCFStack.yaml b/.github/workflows/DeployCFStack.yaml
--- a/.github/workflows/DeployCFStack.yaml
+++ b/.github/workflows/DeployCFStack.yaml
@@ -36,28 +36,28 @@ jobs:
           aws-region: ${{ github.event.inputs.aws-region }}
 
       - name: Create lambda rest api Stack
-        if: ${{ github.event.inputs.cf-template== 'lambda_and_apigateway' }}
+        if: ${{ github.event.inputs.cf-template== 's3bucket' }}
         run: |
           echo "creating lambda function and integrated rest api"
 
           aws cloudformation create-stack \
                         --stack-name ${{ github.event.inputs.stack-name }} \
-                        --template-body file://cf_template/lambda_and_apigateway.yaml \
+                        --template-body file://cf_template/s3bucket.yaml \
                         --region ${{ github.event.inputs.aws-region }}
 
-#           # aws cloudformation wait stack-create-complete \
-#           #               --stack-name ${{ github.event.inputs.stack-name }} \
-#           #               --region ${{ github.event.inputs.aws-region }}
+          aws cloudformation wait stack-create-complete \
+                        --stack-name ${{ github.event.inputs.stack-name }} \
+                        --region ${{ github.event.inputs.aws-region }}
 
-#           # STATUS=$(aws cloudformation wait stack-create-complete \
-#           #               --stack-name ${{ github.event.inputs.stack-name }} \
-#           #               --region ${{ github.event.inputs.aws-region }} \
-#           #               --output=text
-#           #               --query 'Stacks[0].{Status:StackStatus}')
+          STATUS=$(aws cloudformation wait stack-create-complete \
+                        --stack-name ${{ github.event.inputs.stack-name }} \
+                        --region ${{ github.event.inputs.aws-region }} \
+                        --output=text
+                        --query 'Stacks[0].{Status:StackStatus}')
 
-#           # if [ $STATUS = 'CREATE_COMPLETE' ]; then
-#           #     echo "stack creation complete"
-#           # else
-#           #     echo "Stack creation failed"
-#           #     exit 1
-#           # fi 
+          if [ $STATUS = 'CREATE_COMPLETE' ]; then
+              echo "stack creation complete"
+          else
+              echo "Stack creation failed"
+              exit 1
+          fi 
