creating bucket

diff --git a/.github/workflows/DeployCFStack.yaml b/.github/workflows/DeployCFStack.yaml
--- a/.github/workflows/DeployCFStack.yaml
+++ b/.github/workflows/DeployCFStack.yaml
@@ -43,14 +43,14 @@ jobs:
 
           echo ${{ github.event.inputs.cf-template }}
 
-          # aws cloudformation create-stack \
-          #               --stack-name ${{ github.event.inputs.stack-name }} \
-          #               --template-body file://cf_template/s3bucket.yaml \
-          #               --region ${{ github.event.inputs.aws-region }}
+          aws cloudformation create-stack \
+                        --stack-name ${{ github.event.inputs.stack-name }} \
+                        --template-body file://cf_template/s3bucket.yaml \
+                        --region ${{ github.event.inputs.aws-region }}
 
-          # aws cloudformation wait stack-create-complete \
-          #               --stack-name ${{ github.event.inputs.stack-name }} \
-          #               --region ${{ github.event.inputs.aws-region }}
+          aws cloudformation wait stack-create-complete \
+                        --stack-name ${{ github.event.inputs.stack-name }} \
+                        --region ${{ github.event.inputs.aws-region }}
 
           STATUS=$(aws cloudformation wait stack-create-complete \
                         --stack-name ${{ github.event.inputs.stack-name }} \
@@ -69,20 +69,20 @@ jobs:
         if: ${{ github.event.inputs.cf-template== 's3bucket'}}
         run: |
           BUCKET="vb-test-lambda-code-bucket"
-          # STATUS=$(aws cloudformation describe-stacks --region ${{ github.event.inputs.aws-region }} --stack-name ${{ github.event.inputs.stack-name }} --output=text --query 'Stacks[0].{Status:StackStatus}')
-          # echo $STATUS
-          # if [ $STATUS = 'CREATE_COMPLETE' ]; then
-          #   echo "creating package"
+          STATUS=$(aws cloudformation describe-stacks --region ${{ github.event.inputs.aws-region }} --stack-name ${{ github.event.inputs.stack-name }} --output=text --query 'Stacks[0].{Status:StackStatus}')
+          echo $STATUS
+          if [ $STATUS = 'CREATE_COMPLETE' ]; then
+            echo "creating package"
           #   cd ./lambda_code/
           #   zip -r package.zip ./*
           #   echo "Updating lambda code in S3 bucket"
           #   aws s3 cp package.zip s3://${BUCKET}/code/
 
           #   echo "package update successful"
-          # else:
-          #   echo "package updae failed"
-          #   exit 1
-          # fi
+          else:
+            echo "package updae failed"
+            exit 1
+          fi
 
       - name: Create lambda Function and API Gateway
         if: ${{ github.event.inputs.cf-template== 'lambda_and_apigateway' }}
