code update

diff --git a/.github/workflows/DeployCFStack.yaml b/.github/workflows/DeployCFStack.yaml
--- a/.github/workflows/DeployCFStack.yaml
+++ b/.github/workflows/DeployCFStack.yaml
@@ -72,15 +72,15 @@ jobs:
           STATUS=$(aws cloudformation describe-stacks --region ${{ github.event.inputs.aws-region }} --stack-name ${{ github.event.inputs.stack-name }} --output=text --query 'Stacks[0].{Status:StackStatus}')
           echo $STATUS
           if [[ "$STATUS" -eq 'CREATE_COMPLETE' ]]; then
-            echo "creating package"
-            cd ./lambda_code/
-            zip -r package.zip ./*
-            echo "Updating lambda code in S3 bucket"
-            aws s3 cp package.zip s3://${BUCKET}/code/
-            echo "package update successful"
+              echo "creating package"
+              cd ./lambda_code/
+              zip -r package.zip ./*
+              echo "Updating lambda code in S3 bucket"
+              aws s3 cp package.zip s3://${BUCKET}/code/
+              echo "package update successful"
           else:
-            echo "package updae failed"
-            exit 1
+              echo "zip updation failed"
+              exit 1
           fi
 
       - name: Create lambda Function and API Gateway
